# try:
#     print(10 / 0)
# except Exception as e:
#     print(e)
# finally:
# #     print('Done')

# def add(x,y):
#     if y == 0:
#         raise Exception('y is zero')
#     return x/y

# try:
#     add(20,0)
# except Exception as error:
#     print(error)




